### ISSUE TITLE
لیست API

### ISSUE THREAD

**Issue by hamedajoudani** [Hatef-Rostamkhani/OfflineTradingUI2#3]
<div dir=rtl>
لطفا API های داخل لیست پیاده سازی شوند
</div>
[apis.zip](https://github.com/Hatef-Rostamkhani/OfflineTradingUI2/files/3166971/apis.zip)

**Comment by Hatef-Rostamkhani** [comment]
لطفا تو فایل اکسل زمان بندی بشه هر کدام از آنها در چه تاریخی انجام میشه تا بتونیم برای تست برنامه ریزی کنیم
فایل اکسل رو میتونید همین جا آپلود کنید
@mrdimaan
