### ISSUE TITLE
/forget-password

### ISSUE THREAD

**Issue by hamedajoudani** [Hatef-Rostamkhani/OfflineTradingUI2#8]
<div dir=rtl>
پیام خطا نمایش داده نمیشود
</div>

![image](https://user-images.githubusercontent.com/48435519/58328748-20876500-7e48-11e9-86db-8276dac9c364.png)

**Comment by Hatef-Rostamkhani** [comment]
پیام ها از سمت سرور می آید 
اوکی شد
