### ISSUE TITLE
بازیابی کلمه عبور

### ISSUE THREAD

**Issue by hamedajoudani** [Hatef-Rostamkhani/OfflineTradingUI2#9]
<div dir=rtl>
به دلیل اینکه بعد از تغییر پسورد کاربر به صفحه لاگین ریدایرکت میشود و جای کد ملی کد OTP ذخیره شده است مراحل به اینگونه تغییر کند

2 مرحله میشود
1-در مرحله اول فقط OTP گرفته میشود
<
![image](https://user-images.githubusercontent.com/48435519/58328841-59273e80-7e48-11e9-9f2b-597816de1620.png)

2- در مرحله دوم کلمه عبور از کاربر گرفته شود
![image](https://user-images.githubusercontent.com/48435519/58328949-ac00f600-7e48-11e9-93a7-e30a43e18cf7.png)

@Hatef-Rostamkhani 
@roksanaaghajanpoor 
/div>

**Comment by Hatef-Rostamkhani** [comment]
خوبه کد ملی و شماره موبایل در مرحله بعد مخفی بشن
فقط رمز و تکرار رمز نشون داده بشه
